import type {
  Faq,
  GalleryImage,
  Promo,
  Service,
  ServiceCategory,
} from "@/lib/api";

export const staticCategories: ServiceCategory[] = [
  { id: 1, name: "Brows", slug: "brows", icon: "sparkles", description: "Semi-permanent brow artistry — ombre, nano hair strokes and digital combination.", sort_order: 1 },
  { id: 2, name: "Lips", slug: "lips", icon: "heart", description: "Lip tinting and blushing for natural, healthy-looking colour.", sort_order: 2 },
  { id: 3, name: "Lashes", slug: "lashes", icon: "eye", description: "Korean lashliner — semi-permanent lash-line enhancement.", sort_order: 3 },
  { id: 4, name: "Facial Treatments", slug: "facial-treatments", icon: "leaf", description: "Cleansing, diamond peel, acne and hydra facials for healthy glowing skin.", sort_order: 4 },
  { id: 5, name: "Laser & Body", slug: "laser-body", icon: "wand", description: "Pico laser, diode laser, radio frequency and tattoo removal treatments.", sort_order: 5 },
];

const categoryBySlug = Object.fromEntries(
  staticCategories.map((c) => [c.slug, c]),
);

const meta = (title: string, description: string) => ({
  title,
  description,
  keywords: null,
});

export const staticServices: Service[] = [
  {
    id: 1,
    name: "Ombre Microshading Brows",
    slug: "ombre-microshading",
    short_description: "Soft powdered brows with a flawless ombre gradient.",
    description:
      "Ombre Microshading creates a soft, powdered brow that fades from a subtle front to a crisp tail — like a polished daily makeup look that never washes off. Done in two sessions (initial + perfecting), with a 3-month to 1-year touch-up window.",
    price: "7000.00",
    promo_price: "2999.00",
    duration_minutes: 180,
    cover_image: "/images/666957526_1188211739950060_400784778358443402_n.jpg",
    gallery: null,
    benefits: [
      "Soft powdered finish",
      "Ideal for oily skin",
      "Two-session protocol (1st + 2nd)",
      "Touch-up from ₱1,999 (3 months – 1 year)",
    ],
    process_steps: [
      "Consultation & shape mapping",
      "Topical numbing",
      "1st session pigment work",
      "2nd session perfecting (after 4–6 weeks)",
    ],
    aftercare: [
      "Avoid water on brows for 7 days",
      "No makeup on the area for 10 days",
      "Apply healing balm twice daily",
      "Book your 2nd session in 4–6 weeks",
    ],
    meta: meta(
      "Ombre Microshading Brows in Imus Cavite | Emcey Brows",
      "Ombre microshading brows in Imus, Cavite. 1st session from ₱2,999. Soft powdered finish, touch-up from ₱1,999.",
    ),
    is_featured: true,
    category: categoryBySlug["brows"],
  },
  {
    id: 2,
    name: "Digital Nano Hair Strokes",
    slug: "digital-nano-hair-strokes",
    short_description: "Hyper-realistic digital hair-stroke brows, stroke by stroke.",
    description:
      "Digital Nano Hair Strokes use a precision digital machine to draw ultra-fine, hair-like strokes for the most natural brow finish we offer. Best for normal-to-dry skin and clients who want the look of real brow hairs.",
    price: "10000.00",
    promo_price: "4499.00",
    duration_minutes: 180,
    cover_image: "/images/671149180_3306834596163166_5499780834327785454_n.jpg",
    gallery: null,
    benefits: [
      "Most natural hair-stroke realism",
      "Digital precision machine",
      "Two-session protocol",
      "Touch-up from ₱3,499 (3 months – 1 year)",
    ],
    process_steps: [
      "Consultation & shape mapping",
      "Topical numbing",
      "1st session digital strokes",
      "2nd session perfecting (after 4–6 weeks)",
    ],
    aftercare: [
      "Avoid water on brows for 7 days",
      "No makeup on the area for 10 days",
      "Apply healing balm twice daily",
      "Book your 2nd session in 4–6 weeks",
    ],
    meta: meta(
      "Digital Nano Hair Strokes Brows in Imus | Emcey Brows Aesthetics",
      "Digital nano hair-stroke brows in Imus, Cavite. 1st session from ₱4,499. Hyper-realistic hair-stroke finish.",
    ),
    is_featured: true,
    category: categoryBySlug["brows"],
  },
  {
    id: 3,
    name: "Digital Combination Brows",
    slug: "digital-combination-brows",
    short_description: "Hair strokes at the front, ombre at the tail — best of both.",
    description:
      "Digital Combination Brows pair nano hair strokes at the head with a soft ombre shade at the tail — the most flexible result for clients who want defined yet natural brows that suit any skin type.",
    price: "8000.00",
    promo_price: "3699.00",
    duration_minutes: 200,
    cover_image: "/images/670304583_1345528570977679_8758680301644996539_n.jpg",
    gallery: null,
    benefits: [
      "Hair strokes + ombre shading",
      "Suits most skin types",
      "Two-session protocol",
      "Touch-up from ₱2,699 (3 months – 1 year)",
    ],
    process_steps: [
      "Consultation & shape mapping",
      "Topical numbing",
      "1st session strokes + shading",
      "2nd session perfecting (after 4–6 weeks)",
    ],
    aftercare: [
      "Avoid water on brows for 7 days",
      "No makeup on the area for 10 days",
      "Apply healing balm twice daily",
      "Book your 2nd session in 4–6 weeks",
    ],
    meta: meta(
      "Digital Combination Brows in Imus Cavite | Emcey Brows",
      "Digital combination brows in Imus, Cavite. 1st session from ₱3,699. Hair strokes + ombre — best of both.",
    ),
    is_featured: true,
    category: categoryBySlug["brows"],
  },
  {
    id: 4,
    name: "Lip Tinting / Blushing",
    slug: "lip-tinting-blushing",
    short_description: "Soft semi-permanent lip tint with a natural, healthy flush.",
    description:
      "Lip Tinting (Blushing) evens out your natural lip tone and adds a soft, custom blush colour for a healthy, kissed look. Custom shade matched to your skin tone — completed in two sessions.",
    price: "7000.00",
    promo_price: "2999.00",
    duration_minutes: 180,
    cover_image: "/images/671365357_1652344876110909_2196230468653312860_n.jpg",
    gallery: null,
    benefits: [
      "Even, healthy lip tone",
      "Custom blush shade",
      "Two-session protocol",
      "Touch-up from ₱1,999 (3 months – 1 year)",
    ],
    process_steps: [
      "Shade consultation",
      "Topical numbing",
      "1st session pigment work",
      "2nd session perfecting (after 4–6 weeks)",
    ],
    aftercare: [
      "Keep lips dry for the first 24 hours",
      "Apply healing balm hourly for 3 days",
      "Avoid spicy / hot foods for 7 days",
      "Book your 2nd session in 4–6 weeks",
    ],
    meta: meta(
      "Lip Tinting & Blushing in Imus Cavite | Emcey Brows",
      "Semi-permanent lip tinting / blushing in Imus, Cavite. 1st session from ₱2,999. Custom blush shade.",
    ),
    is_featured: true,
    category: categoryBySlug["lips"],
  },
  {
    id: 5,
    name: "Korean Lashliner",
    slug: "korean-lashliner",
    short_description: "Subtle semi-permanent eyeliner along the lash line.",
    description:
      "Korean Lashliner sits at the base of your lashes to create the illusion of fuller, more defined lashes — without daily eyeliner. Soft, natural and wakeup-ready.",
    price: "4000.00",
    promo_price: "1999.00",
    duration_minutes: 120,
    cover_image: "/images/668042950_1019368564256754_3153242901631791560_n.jpg",
    gallery: null,
    benefits: [
      "Defined lash line, no daily liner",
      "Soft natural finish",
      "Two-session protocol",
      "Touch-up from ₱1,999 (3 months – 1 year)",
    ],
    process_steps: [
      "Eye-shape consultation",
      "Topical numbing",
      "1st session lash-line pigment",
      "2nd session perfecting (after 4–6 weeks)",
    ],
    aftercare: [
      "Keep the area dry for 5 days",
      "No eye makeup for 7 days",
      "Apply healing balm twice daily",
      "Book your 2nd session in 4–6 weeks",
    ],
    meta: meta(
      "Korean Lashliner in Imus Cavite | Semi-Permanent Eyeliner",
      "Korean lashliner in Imus, Cavite. 1st session from ₱1,999. Subtle semi-permanent eyeliner along the lash line.",
    ),
    is_featured: true,
    category: categoryBySlug["lashes"],
  },
  {
    id: 6,
    name: "Cleansing Facial",
    slug: "cleansing-facial",
    short_description: "Gentle deep-cleanse facial for healthy, refreshed skin.",
    description:
      "A foundational deep-cleanse facial — exfoliation, gentle extraction and a soothing finish. The starting point for clearer, brighter skin.",
    price: "500.00",
    promo_price: null,
    duration_minutes: 45,
    cover_image: "/images/705153856_26560352726993811_6455456721081485987_n.jpg",
    gallery: null,
    benefits: ["Deep pore cleansing", "Gentle exfoliation", "Soothing finish"],
    process_steps: null,
    aftercare: null,
    meta: meta(
      "Cleansing Facial in Imus Cavite | Emcey Brows Aesthetics",
      "Gentle deep-cleansing facial in Imus, Cavite for clearer, refreshed skin.",
    ),
    is_featured: false,
    category: categoryBySlug["facial-treatments"],
  },
  {
    id: 7,
    name: "Diamond Peel Facial",
    slug: "diamond-peel-facial",
    short_description: "Crystal-free microdermabrasion for instantly smoother skin.",
    description:
      "Diamond Peel is a crystal-free microdermabrasion that gently buffs the top layer of skin — revealing brighter tone and softer texture immediately after.",
    price: "700.00",
    promo_price: null,
    duration_minutes: 60,
    cover_image: "/images/705153856_26560352726993811_6455456721081485987_n.jpg",
    gallery: null,
    benefits: ["Smoother texture", "Brighter tone", "No downtime"],
    process_steps: null,
    aftercare: null,
    meta: meta(
      "Diamond Peel Facial in Imus Cavite | Crystal-Free Microdermabrasion",
      "Diamond peel facial in Imus, Cavite. Crystal-free microdermabrasion for smoother, brighter skin.",
    ),
    is_featured: false,
    category: categoryBySlug["facial-treatments"],
  },
  {
    id: 8,
    name: "Acne Facial",
    slug: "acne-facial",
    short_description: "Targeted facial for active breakouts and oily skin.",
    description:
      "Targeted acne-care protocol for active breakouts and oily, congested skin — gentle deep cleansing, extraction and soothing finish designed for the humid Cavite climate.",
    price: "1200.00",
    promo_price: null,
    duration_minutes: 75,
    cover_image: "/images/705153856_26560352726993811_6455456721081485987_n.jpg",
    gallery: null,
    benefits: ["Calms active breakouts", "Deep pore cleansing", "Suits humid-climate skin"],
    process_steps: null,
    aftercare: null,
    meta: meta(
      "Acne Facial in Imus Cavite | Deep-Cleansing Treatment",
      "Acne facial in Imus, Cavite. A gentle, effective protocol for active breakouts.",
    ),
    is_featured: false,
    category: categoryBySlug["facial-treatments"],
  },
  {
    id: 9,
    name: "Hydra Facial",
    slug: "hydra-facial",
    short_description: "Hydration-boosting facial for dewy, glass-skin glow.",
    description:
      "A multi-step hydra facial that cleanses, exfoliates and floods the skin with hydration for an immediate dewy, glass-skin glow. Suits dehydrated and dull skin.",
    price: "1500.00",
    promo_price: null,
    duration_minutes: 75,
    cover_image: "/images/705153856_26560352726993811_6455456721081485987_n.jpg",
    gallery: null,
    benefits: ["Deep hydration", "Glass-skin glow", "Plumps fine lines"],
    process_steps: null,
    aftercare: null,
    meta: meta(
      "Hydra Facial in Imus Cavite | Hydration Glow Treatment",
      "Hydra facial in Imus, Cavite. Hydration-boosting facial for a dewy glass-skin glow.",
    ),
    is_featured: true,
    category: categoryBySlug["facial-treatments"],
  },
  {
    id: 10,
    name: "Diode Laser Hair Removal",
    slug: "diode-laser-hair-removal",
    short_description: "Permanent hair reduction — underarm, legs, bikini and more.",
    description:
      "Medical-grade diode laser hair removal for long-term hair reduction. Buy-5-get-2-free per area, with a 10+5-free VIP option. Pricing varies by area — underarm from ₱500, full legs from ₱1,200.",
    price: "350.00",
    promo_price: null,
    duration_minutes: 30,
    cover_image: "/images/706473564_1389681486304309_8944739647048307489_n.jpg",
    gallery: null,
    benefits: [
      "Underarm — ₱500",
      "Upper Lip — ₱350",
      "Half Legs — ₱950",
      "Full Legs — ₱1,200",
      "Bikini — ₱650 · Brazilian — ₱1,000",
      "BUY 5 + GET 2 FREE · VIP: BUY 10 + 5 FREE",
    ],
    process_steps: null,
    aftercare: null,
    meta: meta(
      "Diode Laser Hair Removal in Imus Cavite | Emcey Brows",
      "Medical-grade diode laser hair removal in Imus, Cavite. From ₱350. Buy 5 + get 2 free per area.",
    ),
    is_featured: false,
    category: categoryBySlug["laser-body"],
  },
  {
    id: 11,
    name: "Pico Laser Treatments",
    slug: "pico-laser-treatments",
    short_description: "Carbon laser, melasma removal and whitening treatments.",
    description:
      "Pico laser treatments target melasma, dark spots and uneven tone. Includes carbon laser face peel, underarm and elbow whitening, and groin (singit) whitening.",
    price: "700.00",
    promo_price: null,
    duration_minutes: 30,
    cover_image: "/images/706473564_1389681486304309_8944739647048307489_n.jpg",
    gallery: null,
    benefits: [
      "Black Doll Carbon Laser (Face) — ₱900",
      "Melasma / Dark Spots Removal — ₱900",
      "UA Whitening Carbon Laser — ₱700",
      "Elbow Whitening Laser — ₱700",
      "Groin (Singit) Whitening Laser — ₱800",
      "BUY 5 + GET 2 FREE · VIP: BUY 10 + 5 FREE",
    ],
    process_steps: null,
    aftercare: null,
    meta: meta(
      "Pico Laser Treatments in Imus Cavite | Carbon Laser, Whitening",
      "Pico laser treatments in Imus, Cavite. Carbon laser, melasma removal and underarm/elbow whitening from ₱700.",
    ),
    is_featured: true,
    category: categoryBySlug["laser-body"],
  },
  {
    id: 12,
    name: "Radio Frequency Treatments",
    slug: "radio-frequency-treatments",
    short_description: "Non-surgical skin tightening for face and body.",
    description:
      "Radio frequency treatments tighten and contour without surgery. Targets double chin, full face, arms and tummy — buy-5-get-2-free per area, with a 10+5-free VIP option.",
    price: "350.00",
    promo_price: null,
    duration_minutes: 30,
    cover_image: "/images/706473564_1389681486304309_8944739647048307489_n.jpg",
    gallery: null,
    benefits: [
      "Double Chin — ₱350",
      "Full Face — ₱500",
      "Arms — ₱700",
      "Tummy — ₱1,000",
      "BUY 5 + GET 2 FREE · VIP: BUY 10 + 5 FREE",
    ],
    process_steps: null,
    aftercare: null,
    meta: meta(
      "Radio Frequency Treatments in Imus Cavite | Skin Tightening",
      "Radio frequency skin tightening in Imus, Cavite. Double chin, full face, arms and tummy from ₱350.",
    ),
    is_featured: false,
    category: categoryBySlug["laser-body"],
  },
  {
    id: 13,
    name: "Tattoo & Mole Removal",
    slug: "tattoo-mole-removal",
    short_description: "Eyebrow tattoo, body tattoo, warts and milia removal.",
    description:
      "Safe removal of unwanted eyebrow tattoos, body tattoos, warts and milia using electrocautery and tattoo-specific laser protocols.",
    price: "250.00",
    promo_price: null,
    duration_minutes: 30,
    cover_image: "/images/706473564_1389681486304309_8944739647048307489_n.jpg",
    gallery: null,
    benefits: [
      "Eyebrow Tattoo Removal — ₱1,000",
      "Body Tattoo (per area) — ₱1,200",
      "Warts (per piece, big) — ₱300",
      "Warts (Unlimited Face & Neck) — ₱2,500",
      "Milia Removal (per pc) — ₱250",
    ],
    process_steps: null,
    aftercare: null,
    meta: meta(
      "Tattoo & Mole Removal in Imus Cavite | Emcey Brows",
      "Eyebrow tattoo removal, body tattoo, warts and milia removal in Imus, Cavite.",
    ),
    is_featured: false,
    category: categoryBySlug["laser-body"],
  },
];

export const staticFaqs: Faq[] = [
  { id: 1, category: "General", question: "Where is Emcey Brows Aesthetics located?", answer: "We are located on the 2nd Floor of Brigitte Optical Center Commercial Building, Block 2 Lot 14 Piazza Bellissima, Anabu-1D Aguinaldo Highway, Imus, Cavite.", sort_order: 1, service_id: null },
  { id: 2, category: "General", question: "Do you accept walk-ins?", answer: "Yes, but we strongly recommend booking online so we can prepare your time slot and tools.", sort_order: 2, service_id: null },
  { id: 3, category: "General", question: "Do you offer down payments?", answer: "Yes. A small reservation fee secures your booking and is deducted from your final bill.", sort_order: 3, service_id: null },
  { id: 4, category: "General", question: "Is the studio hygienic?", answer: "Absolutely. We use single-use needles, sterilised tools and follow medical-grade hygiene standards.", sort_order: 4, service_id: null },
  { id: 5, category: "General", question: "Do you have a payment plan?", answer: "We accept GCash, Maya, cash and partial down payment online.", sort_order: 5, service_id: null },
  { id: 6, category: "Pricing", question: "Why are there two sessions for semi-permanent makeup?", answer: "Every PMU treatment (brows, lips, lashliner) is a two-session protocol: the 1st session lays down the colour and shape, and the 2nd perfecting session (4–6 weeks later) refines the result after your skin has healed.", sort_order: 6, service_id: null },
  { id: 7, category: "Pricing", question: "What is the difference between Sr Artist and Master Artist rates?", answer: "Master Artist rate is an additional ₱1,500 for the 1st session, ₱1,000 for the 2nd session, and ₱1,500 for semi-annual touch-ups.", sort_order: 7, service_id: null },

  // Service-specific
  { id: 8, category: "Ombre Microshading", question: "Does ombre microshading hurt?", answer: "We use a topical numbing cream so most clients feel only light pressure during the session.", sort_order: 1, service_id: 1 },
  { id: 9, category: "Ombre Microshading", question: "How long does ombre microshading last?", answer: "Typically 1–2 years. We offer touch-ups from ₱1,999 between 3 months and 1 year after your perfecting session.", sort_order: 2, service_id: 1 },
  { id: 10, category: "Digital Nano Hair Strokes", question: "Who are nano hair strokes best for?", answer: "Best for normal-to-dry skin and clients who want the most natural-looking, hair-by-hair brow result.", sort_order: 1, service_id: 2 },
  { id: 11, category: "Digital Combination Brows", question: "What's the difference between combination and ombre brows?", answer: "Combination brows pair hair strokes at the front with ombre shading at the tail — most flexible, suits most skin types. Ombre is fully powdered and better for oily skin.", sort_order: 1, service_id: 3 },
  { id: 12, category: "Lip Tinting / Blushing", question: "Will my lips look red right after?", answer: "Yes — colour appears brighter for 3–5 days, then softens to your customised shade.", sort_order: 1, service_id: 4 },
  { id: 13, category: "Korean Lashliner", question: "Is Korean Lashliner the same as permanent eyeliner?", answer: "Lashliner sits between the lashes (along the lash base) for a subtle defined-lash look. It's softer and more natural than a traditional eyeliner tattoo.", sort_order: 1, service_id: 5 },
  { id: 14, category: "Diode Laser", question: "How many sessions do I need for hair removal?", answer: "Most clients see significant reduction after the buy-5-get-2-free package. VIP buy-10-get-5-free is for longer-term clearing.", sort_order: 1, service_id: 10 },
];

const serviceRef = (slug: string) => {
  const s = staticServices.find((x) => x.slug === slug);
  return s ? { id: s.id, name: s.name, slug: s.slug } : null;
};

export const staticGallery: GalleryImage[] = [
  {
    id: 1,
    category: "Brows",
    title: "Ombre microshading — soft gradient",
    alt_text: "Ombre microshading before and after, soft gradient finish, Imus Cavite",
    image_path: "/images/705373172_2820942641600337_7339268553663447641_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: true,
    service: serviceRef("ombre-microshading"),
  },
  {
    id: 2,
    category: "Brows",
    title: "Digital combination — natural definition",
    alt_text: "Digital combination brows before and after, hair strokes plus ombre, Imus Cavite",
    image_path: "/images/563379944_1559363695053661_1254350415973776143_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: true,
    service: serviceRef("digital-combination-brows"),
  },
  {
    id: 3,
    category: "Brows",
    title: "Powder brows — defined arch",
    alt_text: "Powder brows result, natural defined arch by Emcey Brows Imus Cavite",
    image_path: "/images/566511023_1146226867043391_5455139529089946125_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: true,
    service: serviceRef("ombre-microshading"),
  },
  {
    id: 4,
    category: "Brows",
    title: "Microshading — masked client",
    alt_text: "Ombre microshading before and after, masked client, Imus Cavite",
    image_path: "/images/617573516_900360955780444_8416221202445316314_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: false,
    service: serviceRef("ombre-microshading"),
  },
  {
    id: 5,
    category: "Brows",
    title: "Healed 1st session → 2nd session",
    alt_text: "Ombre brows healed first session and second session result, Emcey Brows Imus Cavite",
    image_path: "/images/705520167_926881460374361_1069724535191431360_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: false,
    service: serviceRef("ombre-microshading"),
  },
  {
    id: 6,
    category: "Brows",
    title: "Crisp arch — healed result",
    alt_text: "Crisp ombre brow arch healed result, Imus Cavite client",
    image_path: "/images/652319019_790683164107444_7349255575650557644_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: false,
    service: serviceRef("ombre-microshading"),
  },
  {
    id: 7,
    category: "Lips",
    title: "Lip blushing — soft rose",
    alt_text: "Lip tinting and blushing result, soft rose tint, Imus Cavite",
    image_path: "/images/706718272_1942984493012627_4541287178627539398_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: true,
    service: serviceRef("lip-tinting-blushing"),
  },
  {
    id: 8,
    category: "Lips",
    title: "Lip blushing — healed natural tone",
    alt_text: "Lip blushing healed result, custom blush tint, Imus Cavite",
    image_path: "/images/563602481_1526465715026962_3442888535669137838_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: false,
    service: serviceRef("lip-tinting-blushing"),
  },
  {
    id: 9,
    category: "Facial",
    title: "Facial treatment session",
    alt_text: "Facial treatment in progress at Emcey Brows Aesthetics, Imus Cavite",
    image_path: "/images/705153856_26560352726993811_6455456721081485987_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: true,
    service: serviceRef("hydra-facial"),
  },
  {
    id: 10,
    category: "Studio",
    title: "Inside the studio",
    alt_text: "Emcey Brows Aesthetics studio interior, Imus Cavite",
    image_path: "/images/hero/tile-1.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: false,
    service: null,
  },
  {
    id: 11,
    category: "Studio",
    title: "Reception area",
    alt_text: "Emcey Brows Aesthetics reception area, Imus Cavite",
    image_path: "/images/706703575_4480213738924616_3954472543166964580_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: false,
    service: null,
  },
  {
    id: 12,
    category: "Studio",
    title: "Treatment room",
    alt_text: "Emcey Brows Aesthetics treatment room, Imus Cavite",
    image_path: "/images/707012275_1039838768610469_977160467361222562_n.jpg",
    before_image_path: null,
    after_image_path: null,
    is_featured: false,
    service: null,
  },
];

export const staticPromos: Promo[] = [
  {
    id: 1,
    code: "COMBO-OMB-LASH",
    title: "Ombre Microshading + Korean Lashliner",
    description: "Combo Package 1 — was ₱11,000, now ₱4,699 (1st session price only).",
    type: "fixed",
    value: "6301.00",
    minimum_amount: null,
    cover_image: "/images/705235475_1013448067793096_1728925701428008618_n.jpg",
    starts_at: null,
    ends_at: null,
    is_featured: true,
  },
  {
    id: 2,
    code: "COMBO-OMB-LIP",
    title: "Ombre Microshading + Lip Tinting / Blushing",
    description: "Combo Package 2 — was ₱14,000, now ₱5,699 (1st session price only).",
    type: "fixed",
    value: "8301.00",
    minimum_amount: null,
    cover_image: "/images/705235475_1013448067793096_1728925701428008618_n.jpg",
    starts_at: null,
    ends_at: null,
    is_featured: true,
  },
  {
    id: 3,
    code: "COMBO-LIP-LASH",
    title: "Lip Tinting / Blushing + Korean Lashliner",
    description: "Combo Package 3 — was ₱11,000, now ₱4,699 (1st session price only).",
    type: "fixed",
    value: "6301.00",
    minimum_amount: null,
    cover_image: "/images/705235475_1013448067793096_1728925701428008618_n.jpg",
    starts_at: null,
    ends_at: null,
    is_featured: false,
  },
  {
    id: 4,
    code: "COMBO-TRIO",
    title: "Brows + Lips + Lashes (Trio)",
    description: "Combo Package 4 — Ombre Microshading + Korean Lashliner + Liptinting/Blushing for ₱7,499 (1st session price only).",
    type: "fixed",
    value: "8501.00",
    minimum_amount: null,
    cover_image: "/images/705235475_1013448067793096_1728925701428008618_n.jpg",
    starts_at: null,
    ends_at: null,
    is_featured: true,
  },
  {
    id: 5,
    code: "VIP-WHITENING",
    title: "VIP Whitening Bundle",
    description: "10 sessions UA Whitening + 10 sessions Rejuvenation + 10 sessions UA Hair Removal — ₱9,999.",
    type: "fixed",
    value: "0.00",
    minimum_amount: null,
    cover_image: "/images/706473564_1389681486304309_8944739647048307489_n.jpg",
    starts_at: null,
    ends_at: null,
    is_featured: false,
  },
];

export const filterFeatured = <T extends { is_featured: boolean }>(items: T[]) =>
  items.filter((i) => i.is_featured);
